const API="https://api.sleeper.app/v1",SEASON="2026";let S={user:null,leagues:[],rows:[],players:{}};const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{$("username").value=localStorage.getItem("fcc_username")||"Txeagle";$("loadBtn").onclick=load;$("refreshBtn").onclick=load;$("leagueSelect").onchange=renderTeam;$("playerSearch").oninput=renderSearch;document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.view).classList.add("active")});if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js");load()});
async function get(u){let r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(r.status+" "+r.statusText);return r.json()}
async function load(){let username=$("username").value.trim();if(!username)return;localStorage.setItem("fcc_username",username);status("Loading "+username+"…");try{let user=await get(API+"/user/"+encodeURIComponent(username));if(!user?.user_id)throw Error("Sleeper user not found");S.user=user;S.leagues=await get(API+"/user/"+user.user_id+"/leagues/nfl/"+SEASON);S.players=await get(API+"/players/nfl");S.rows=[];let data=await Promise.all(S.leagues.map(async l=>{try{return{l,rs:await get(API+"/league/"+l.league_id+"/rosters")}}catch{return{l,rs:[]}}}));data.forEach(({l,rs})=>{let r=rs.find(x=>x.owner_id===user.user_id);if(!r)return;let st=new Set(r.starters||[]),ir=new Set(r.reserve||[]),tx=new Set(r.taxi||[]);(r.players||[]).forEach(id=>{let p=S.players[id]||{},rosterStatus=ir.has(id)?"IR":tx.has(id)?"Taxi":st.has(id)?"Starter":"Bench";S.rows.push({leagueId:l.league_id,league:l.name,id,name:p.full_name||((p.first_name||"")+" "+(p.last_name||"")).trim()||id,pos:p.position||"",team:p.team||"",rosterStatus,injury:p.injury_status||"",nflStatus:p.status||""})})});renderAll();status((user.display_name||user.username)+" • "+S.leagues.length+" leagues • "+new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"}))}catch(e){status("Could not load: "+e.message)}}
const norm=v=>String(v||"").trim().toLowerCase();const must=r=>["o","out","ir","injured reserve","pup","susp","suspended"].includes(norm(r.injury))||norm(r.nflStatus)==="inactive";const watch=r=>["q","questionable","d","doubtful"].includes(norm(r.injury));const injured=r=>must(r)||watch(r)||!!norm(r.injury);
function renderAll(){renderHome();renderLeagueSelect();renderTeam();renderSearch();renderExposure()}
function renderHome(){let starters=S.rows.filter(r=>r.rosterStatus==="Starter"),m=starters.filter(must),w=starters.filter(watch),map={};starters.filter(injured).forEach(r=>{if(!map[r.id])map[r.id]={...r,leagues:[]};map[r.id].leagues.push(r.league)});let risks=Object.values(map).filter(r=>r.leagues.length>1).sort((a,b)=>b.leagues.length-a.leagues.length);$("leagueCount").textContent=S.leagues.length;$("mustFixCount").textContent=m.length;$("watchCount").textContent=w.length;$("riskCount").textContent=risks.length;$("mustFixList").innerHTML=m.length?m.map(card).join(""):'<div class="muted">✅ No must-change starters.</div>';$("watchList").innerHTML=w.length?w.map(card).join(""):'<div class="muted">✅ No Q/D starters.</div>';$("riskList").innerHTML=risks.length?risks.map(r=>'<div class="player"><span class="badge">'+esc(r.injury)+'</span><div class="player-name">'+esc(r.name)+'</div><div class="sub">'+esc(r.pos)+' • '+esc(r.team||"FA")+' • Starting in '+r.leagues.length+' leagues</div><div>'+r.leagues.map(x=>'<span class="league-chip">'+esc(x)+'</span>').join("")+'</div></div>').join(""):'<div class="muted">✅ No multi-league injury risks.</div>'}
function card(r){return'<div class="player"><span class="badge">'+esc(r.injury||r.nflStatus)+'</span><div class="player-name">'+esc(r.name)+'</div><div class="sub">'+esc(r.pos)+' • '+esc(r.team||"FA")+'<br>'+esc(r.league)+'</div></div>'}
function renderLeagueSelect(){let s=$("leagueSelect"),old=s.value;s.innerHTML=S.leagues.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(l=>'<option value="'+esc(l.league_id)+'">'+esc(l.name)+'</option>').join("");if([...s.options].some(o=>o.value===old))s.value=old}
function renderTeam(){let id=$("leagueSelect").value,rows=S.rows.filter(r=>r.leagueId===id),groups=["Starter","Bench","IR","Taxi"];$("teamRoster").innerHTML=groups.map(g=>{let a=rows.filter(r=>r.rosterStatus===g);if(!a.length)return"";return'<section class="roster-group"><div class="roster-title">'+g.toUpperCase()+'</div><div class="card">'+a.map(r=>'<div class="roster-row"><div class="pos">'+esc(r.pos)+'</div><div><div class="player-name">'+esc(r.name)+'</div><div class="sub">'+esc(r.team||"FA")+(r.injury?' • '+esc(r.injury):'')+'</div></div><div class="sub">'+g+'</div></div>').join("")+'</div></section>'}).join("")}
function renderSearch(){let q=norm($("playerSearch").value);if(!q){$("playerResults").innerHTML='<div class="muted">Type a player name.</div>';return}let a=S.rows.filter(r=>norm(r.name).includes(q));$("playerResults").innerHTML=a.length?a.map(r=>'<div class="player"><span class="badge">'+esc(r.injury)+'</span><div class="player-name">'+esc(r.name)+'</div><div class="sub">'+esc(r.pos)+' • '+esc(r.team||"FA")+'<br>'+esc(r.league)+' • '+r.rosterStatus+'</div></div>').join(""):'<div class="muted">No match.</div>'}
function renderExposure(){let m={};S.rows.forEach(r=>{if(!m[r.id])m[r.id]={...r,owned:new Set(),starts:new Set()};m[r.id].owned.add(r.leagueId);if(r.rosterStatus==="Starter")m[r.id].starts.add(r.leagueId)});$("exposureList").innerHTML=Object.values(m).sort((a,b)=>b.owned.size-a.owned.size||b.starts.size-a.starts.size).map(r=>'<div class="player"><span class="badge">'+esc(r.injury)+'</span><div class="player-name">'+esc(r.name)+'</div><div class="sub">'+esc(r.pos)+' • '+esc(r.team||"FA")+'<br>Owned '+r.owned.size+' • Starting '+r.starts.size+'</div></div>').join("")}
function status(t){$("statusText").textContent=t}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}